reconf_parameter: hadoop.rpc.protection
component: hdfs:JournalNode
v1: integrity
v2: authentication
testProject: hdfs
unitTest: org.apache.hadoop.hdfs.qjournal.TestSecureNNWithQJM#testSecondaryNameNodeHttpAddressNotNeeded
reconfPoint: -2
result: -1

Test vvMode=v1v2
tr.result is -1
v1v2 test failed !!!
reconf_parameter: hadoop.rpc.protection
component: hdfs:JournalNode
v1: integrity
v2: authentication
testProject: hdfs
unitTest: org.apache.hadoop.hdfs.qjournal.TestSecureNNWithQJM#testSecondaryNameNodeHttpAddressNotNeeded
reconfPoint: -2
result: -1
failureMessage: Time out while waiting for journal node 0 to start.
stackTrace: java.lang.AssertionError: Time out while waiting for journal node 0 to start.
	at org.junit.Assert.fail(Assert.java:88)
	at org.apache.hadoop.hdfs.qjournal.MiniJournalCluster.waitActive(MiniJournalCluster.java:258)
	at org.apache.hadoop.hdfs.qjournal.TestSecureNNWithQJM.startCluster(TestSecureNNWithQJM.java:221)
	at org.apache.hadoop.hdfs.qjournal.TestSecureNNWithQJM.doNNWithQJMTest(TestSecureNNWithQJM.java:186)
	at org.apache.hadoop.hdfs.qjournal.TestSecureNNWithQJM.testSecondaryNameNodeHttpAddressNotNeeded(TestSecureNNWithQJM.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)



Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is -1
v1v2 test failed !!!
reconf_parameter: hadoop.rpc.protection
component: hdfs:JournalNode
v1: integrity
v2: authentication
testProject: hdfs
unitTest: org.apache.hadoop.hdfs.qjournal.TestSecureNNWithQJM#testSecondaryNameNodeHttpAddressNotNeeded
reconfPoint: -2
result: -1
failureMessage: Time out while waiting for journal node 0 to start.
stackTrace: java.lang.AssertionError: Time out while waiting for journal node 0 to start.
	at org.junit.Assert.fail(Assert.java:88)
	at org.apache.hadoop.hdfs.qjournal.MiniJournalCluster.waitActive(MiniJournalCluster.java:258)
	at org.apache.hadoop.hdfs.qjournal.TestSecureNNWithQJM.startCluster(TestSecureNNWithQJM.java:221)
	at org.apache.hadoop.hdfs.qjournal.TestSecureNNWithQJM.doNNWithQJMTest(TestSecureNNWithQJM.java:186)
	at org.apache.hadoop.hdfs.qjournal.TestSecureNNWithQJM.testSecondaryNameNodeHttpAddressNotNeeded(TestSecureNNWithQJM.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)



Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is -1
v1v2 test failed !!!
reconf_parameter: hadoop.rpc.protection
component: hdfs:JournalNode
v1: integrity
v2: authentication
testProject: hdfs
unitTest: org.apache.hadoop.hdfs.qjournal.TestSecureNNWithQJM#testSecondaryNameNodeHttpAddressNotNeeded
reconfPoint: -2
result: -1
failureMessage: Time out while waiting for journal node 0 to start.
stackTrace: java.lang.AssertionError: Time out while waiting for journal node 0 to start.
	at org.junit.Assert.fail(Assert.java:88)
	at org.apache.hadoop.hdfs.qjournal.MiniJournalCluster.waitActive(MiniJournalCluster.java:258)
	at org.apache.hadoop.hdfs.qjournal.TestSecureNNWithQJM.startCluster(TestSecureNNWithQJM.java:221)
	at org.apache.hadoop.hdfs.qjournal.TestSecureNNWithQJM.doNNWithQJMTest(TestSecureNNWithQJM.java:186)
	at org.apache.hadoop.hdfs.qjournal.TestSecureNNWithQJM.testSecondaryNameNodeHttpAddressNotNeeded(TestSecureNNWithQJM.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)



Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is -1
v1v2 test failed !!!
reconf_parameter: hadoop.rpc.protection
component: hdfs:JournalNode
v1: integrity
v2: authentication
testProject: hdfs
unitTest: org.apache.hadoop.hdfs.qjournal.TestSecureNNWithQJM#testSecondaryNameNodeHttpAddressNotNeeded
reconfPoint: -2
result: -1
failureMessage: Time out while waiting for journal node 0 to start.
stackTrace: java.lang.AssertionError: Time out while waiting for journal node 0 to start.
	at org.junit.Assert.fail(Assert.java:88)
	at org.apache.hadoop.hdfs.qjournal.MiniJournalCluster.waitActive(MiniJournalCluster.java:258)
	at org.apache.hadoop.hdfs.qjournal.TestSecureNNWithQJM.startCluster(TestSecureNNWithQJM.java:221)
	at org.apache.hadoop.hdfs.qjournal.TestSecureNNWithQJM.doNNWithQJMTest(TestSecureNNWithQJM.java:186)
	at org.apache.hadoop.hdfs.qjournal.TestSecureNNWithQJM.testSecondaryNameNodeHttpAddressNotNeeded(TestSecureNNWithQJM.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)



Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is -1
v1v2 test failed !!!
reconf_parameter: hadoop.rpc.protection
component: hdfs:JournalNode
v1: integrity
v2: authentication
testProject: hdfs
unitTest: org.apache.hadoop.hdfs.qjournal.TestSecureNNWithQJM#testSecondaryNameNodeHttpAddressNotNeeded
reconfPoint: -2
result: -1
failureMessage: Time out while waiting for journal node 0 to start.
stackTrace: java.lang.AssertionError: Time out while waiting for journal node 0 to start.
	at org.junit.Assert.fail(Assert.java:88)
	at org.apache.hadoop.hdfs.qjournal.MiniJournalCluster.waitActive(MiniJournalCluster.java:258)
	at org.apache.hadoop.hdfs.qjournal.TestSecureNNWithQJM.startCluster(TestSecureNNWithQJM.java:221)
	at org.apache.hadoop.hdfs.qjournal.TestSecureNNWithQJM.doNNWithQJMTest(TestSecureNNWithQJM.java:186)
	at org.apache.hadoop.hdfs.qjournal.TestSecureNNWithQJM.testSecondaryNameNodeHttpAddressNotNeeded(TestSecureNNWithQJM.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)



Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is -1
v1v2 test failed !!!
reconf_parameter: hadoop.rpc.protection
component: hdfs:JournalNode
v1: integrity
v2: authentication
testProject: hdfs
unitTest: org.apache.hadoop.hdfs.qjournal.TestSecureNNWithQJM#testSecondaryNameNodeHttpAddressNotNeeded
reconfPoint: -2
result: -1
failureMessage: Time out while waiting for journal node 0 to start.
stackTrace: java.lang.AssertionError: Time out while waiting for journal node 0 to start.
	at org.junit.Assert.fail(Assert.java:88)
	at org.apache.hadoop.hdfs.qjournal.MiniJournalCluster.waitActive(MiniJournalCluster.java:258)
	at org.apache.hadoop.hdfs.qjournal.TestSecureNNWithQJM.startCluster(TestSecureNNWithQJM.java:221)
	at org.apache.hadoop.hdfs.qjournal.TestSecureNNWithQJM.doNNWithQJMTest(TestSecureNNWithQJM.java:186)
	at org.apache.hadoop.hdfs.qjournal.TestSecureNNWithQJM.testSecondaryNameNodeHttpAddressNotNeeded(TestSecureNNWithQJM.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)



Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is -1
v1v2 test failed !!!
reconf_parameter: hadoop.rpc.protection
component: hdfs:JournalNode
v1: integrity
v2: authentication
testProject: hdfs
unitTest: org.apache.hadoop.hdfs.qjournal.TestSecureNNWithQJM#testSecondaryNameNodeHttpAddressNotNeeded
reconfPoint: -2
result: -1
failureMessage: Time out while waiting for journal node 0 to start.
stackTrace: java.lang.AssertionError: Time out while waiting for journal node 0 to start.
	at org.junit.Assert.fail(Assert.java:88)
	at org.apache.hadoop.hdfs.qjournal.MiniJournalCluster.waitActive(MiniJournalCluster.java:258)
	at org.apache.hadoop.hdfs.qjournal.TestSecureNNWithQJM.startCluster(TestSecureNNWithQJM.java:221)
	at org.apache.hadoop.hdfs.qjournal.TestSecureNNWithQJM.doNNWithQJMTest(TestSecureNNWithQJM.java:186)
	at org.apache.hadoop.hdfs.qjournal.TestSecureNNWithQJM.testSecondaryNameNodeHttpAddressNotNeeded(TestSecureNNWithQJM.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)



Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is -1
v1v2 test failed !!!
reconf_parameter: hadoop.rpc.protection
component: hdfs:JournalNode
v1: integrity
v2: authentication
testProject: hdfs
unitTest: org.apache.hadoop.hdfs.qjournal.TestSecureNNWithQJM#testSecondaryNameNodeHttpAddressNotNeeded
reconfPoint: -2
result: -1
failureMessage: Time out while waiting for journal node 0 to start.
stackTrace: java.lang.AssertionError: Time out while waiting for journal node 0 to start.
	at org.junit.Assert.fail(Assert.java:88)
	at org.apache.hadoop.hdfs.qjournal.MiniJournalCluster.waitActive(MiniJournalCluster.java:258)
	at org.apache.hadoop.hdfs.qjournal.TestSecureNNWithQJM.startCluster(TestSecureNNWithQJM.java:221)
	at org.apache.hadoop.hdfs.qjournal.TestSecureNNWithQJM.doNNWithQJMTest(TestSecureNNWithQJM.java:186)
	at org.apache.hadoop.hdfs.qjournal.TestSecureNNWithQJM.testSecondaryNameNodeHttpAddressNotNeeded(TestSecureNNWithQJM.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)



Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is -1
v1v2 test failed !!!
reconf_parameter: hadoop.rpc.protection
component: hdfs:JournalNode
v1: integrity
v2: authentication
testProject: hdfs
unitTest: org.apache.hadoop.hdfs.qjournal.TestSecureNNWithQJM#testSecondaryNameNodeHttpAddressNotNeeded
reconfPoint: -2
result: -1
failureMessage: Time out while waiting for journal node 0 to start.
stackTrace: java.lang.AssertionError: Time out while waiting for journal node 0 to start.
	at org.junit.Assert.fail(Assert.java:88)
	at org.apache.hadoop.hdfs.qjournal.MiniJournalCluster.waitActive(MiniJournalCluster.java:258)
	at org.apache.hadoop.hdfs.qjournal.TestSecureNNWithQJM.startCluster(TestSecureNNWithQJM.java:221)
	at org.apache.hadoop.hdfs.qjournal.TestSecureNNWithQJM.doNNWithQJMTest(TestSecureNNWithQJM.java:186)
	at org.apache.hadoop.hdfs.qjournal.TestSecureNNWithQJM.testSecondaryNameNodeHttpAddressNotNeeded(TestSecureNNWithQJM.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)



Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is -1
v1v2 test failed !!!
reconf_parameter: hadoop.rpc.protection
component: hdfs:JournalNode
v1: integrity
v2: authentication
testProject: hdfs
unitTest: org.apache.hadoop.hdfs.qjournal.TestSecureNNWithQJM#testSecondaryNameNodeHttpAddressNotNeeded
reconfPoint: -2
result: -1
failureMessage: Time out while waiting for journal node 0 to start.
stackTrace: java.lang.AssertionError: Time out while waiting for journal node 0 to start.
	at org.junit.Assert.fail(Assert.java:88)
	at org.apache.hadoop.hdfs.qjournal.MiniJournalCluster.waitActive(MiniJournalCluster.java:258)
	at org.apache.hadoop.hdfs.qjournal.TestSecureNNWithQJM.startCluster(TestSecureNNWithQJM.java:221)
	at org.apache.hadoop.hdfs.qjournal.TestSecureNNWithQJM.doNNWithQJMTest(TestSecureNNWithQJM.java:186)
	at org.apache.hadoop.hdfs.qjournal.TestSecureNNWithQJM.testSecondaryNameNodeHttpAddressNotNeeded(TestSecureNNWithQJM.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)



Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1
early stop after 10 is satisfied
v1v2 failed with probability 10 out of 10
v1v1v2v2 failed with probability 0 out of 10
result: might be true error
Total execution time in seconds : 1122
