reconf_parameter: hadoop.rpc.protection
component: hdfs:Mover
v1: authentication
v2: integrity
testProject: hdfs
unitTest: org.apache.hadoop.hdfs.server.mover.TestMover#testMoverWithKeytabs
reconfPoint: -3
result: -1

Test vvMode=v1v2
tr.result is -1
v1v2 test failed !!!
reconf_parameter: hadoop.rpc.protection
component: hdfs:Mover
v1: authentication
v2: integrity
testProject: hdfs
unitTest: org.apache.hadoop.hdfs.server.mover.TestMover#testMoverWithKeytabs
reconfPoint: -3
result: -1
failureMessage: Movement to ARCHIVE should be successful expected:<0> but was:<-3>
stackTrace: java.lang.AssertionError: Movement to ARCHIVE should be successful expected:<0> but was:<-3>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.apache.hadoop.hdfs.server.mover.TestMover.testWithinSameNode(TestMover.java:201)
	at org.apache.hadoop.hdfs.server.mover.TestMover.access$100(TestMover.java:101)
	at org.apache.hadoop.hdfs.server.mover.TestMover$3.run(TestMover.java:1017)
	at org.apache.hadoop.hdfs.server.mover.TestMover$3.run(TestMover.java:1013)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
	at org.apache.hadoop.hdfs.server.mover.TestMover.testMoverWithKeytabs(TestMover.java:1013)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)



Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is -1
v1v2 test failed !!!
reconf_parameter: hadoop.rpc.protection
component: hdfs:Mover
v1: authentication
v2: integrity
testProject: hdfs
unitTest: org.apache.hadoop.hdfs.server.mover.TestMover#testMoverWithKeytabs
reconfPoint: -3
result: -1
failureMessage: Movement to ARCHIVE should be successful expected:<0> but was:<-3>
stackTrace: java.lang.AssertionError: Movement to ARCHIVE should be successful expected:<0> but was:<-3>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.apache.hadoop.hdfs.server.mover.TestMover.testWithinSameNode(TestMover.java:201)
	at org.apache.hadoop.hdfs.server.mover.TestMover.access$100(TestMover.java:101)
	at org.apache.hadoop.hdfs.server.mover.TestMover$3.run(TestMover.java:1017)
	at org.apache.hadoop.hdfs.server.mover.TestMover$3.run(TestMover.java:1013)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
	at org.apache.hadoop.hdfs.server.mover.TestMover.testMoverWithKeytabs(TestMover.java:1013)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)



Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is -1
v1v2 test failed !!!
reconf_parameter: hadoop.rpc.protection
component: hdfs:Mover
v1: authentication
v2: integrity
testProject: hdfs
unitTest: org.apache.hadoop.hdfs.server.mover.TestMover#testMoverWithKeytabs
reconfPoint: -3
result: -1
failureMessage: Movement to ARCHIVE should be successful expected:<0> but was:<-3>
stackTrace: java.lang.AssertionError: Movement to ARCHIVE should be successful expected:<0> but was:<-3>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.apache.hadoop.hdfs.server.mover.TestMover.testWithinSameNode(TestMover.java:201)
	at org.apache.hadoop.hdfs.server.mover.TestMover.access$100(TestMover.java:101)
	at org.apache.hadoop.hdfs.server.mover.TestMover$3.run(TestMover.java:1017)
	at org.apache.hadoop.hdfs.server.mover.TestMover$3.run(TestMover.java:1013)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
	at org.apache.hadoop.hdfs.server.mover.TestMover.testMoverWithKeytabs(TestMover.java:1013)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)



Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is -1
v1v2 test failed !!!
reconf_parameter: hadoop.rpc.protection
component: hdfs:Mover
v1: authentication
v2: integrity
testProject: hdfs
unitTest: org.apache.hadoop.hdfs.server.mover.TestMover#testMoverWithKeytabs
reconfPoint: -3
result: -1
failureMessage: Movement to ARCHIVE should be successful expected:<0> but was:<-3>
stackTrace: java.lang.AssertionError: Movement to ARCHIVE should be successful expected:<0> but was:<-3>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.apache.hadoop.hdfs.server.mover.TestMover.testWithinSameNode(TestMover.java:201)
	at org.apache.hadoop.hdfs.server.mover.TestMover.access$100(TestMover.java:101)
	at org.apache.hadoop.hdfs.server.mover.TestMover$3.run(TestMover.java:1017)
	at org.apache.hadoop.hdfs.server.mover.TestMover$3.run(TestMover.java:1013)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
	at org.apache.hadoop.hdfs.server.mover.TestMover.testMoverWithKeytabs(TestMover.java:1013)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)



Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is -1
v1v2 test failed !!!
reconf_parameter: hadoop.rpc.protection
component: hdfs:Mover
v1: authentication
v2: integrity
testProject: hdfs
unitTest: org.apache.hadoop.hdfs.server.mover.TestMover#testMoverWithKeytabs
reconfPoint: -3
result: -1
failureMessage: Movement to ARCHIVE should be successful expected:<0> but was:<-3>
stackTrace: java.lang.AssertionError: Movement to ARCHIVE should be successful expected:<0> but was:<-3>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.apache.hadoop.hdfs.server.mover.TestMover.testWithinSameNode(TestMover.java:201)
	at org.apache.hadoop.hdfs.server.mover.TestMover.access$100(TestMover.java:101)
	at org.apache.hadoop.hdfs.server.mover.TestMover$3.run(TestMover.java:1017)
	at org.apache.hadoop.hdfs.server.mover.TestMover$3.run(TestMover.java:1013)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
	at org.apache.hadoop.hdfs.server.mover.TestMover.testMoverWithKeytabs(TestMover.java:1013)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)



Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is -1
v1v2 test failed !!!
reconf_parameter: hadoop.rpc.protection
component: hdfs:Mover
v1: authentication
v2: integrity
testProject: hdfs
unitTest: org.apache.hadoop.hdfs.server.mover.TestMover#testMoverWithKeytabs
reconfPoint: -3
result: -1
failureMessage: Movement to ARCHIVE should be successful expected:<0> but was:<-3>
stackTrace: java.lang.AssertionError: Movement to ARCHIVE should be successful expected:<0> but was:<-3>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.apache.hadoop.hdfs.server.mover.TestMover.testWithinSameNode(TestMover.java:201)
	at org.apache.hadoop.hdfs.server.mover.TestMover.access$100(TestMover.java:101)
	at org.apache.hadoop.hdfs.server.mover.TestMover$3.run(TestMover.java:1017)
	at org.apache.hadoop.hdfs.server.mover.TestMover$3.run(TestMover.java:1013)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
	at org.apache.hadoop.hdfs.server.mover.TestMover.testMoverWithKeytabs(TestMover.java:1013)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)



Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is -1
v1v2 test failed !!!
reconf_parameter: hadoop.rpc.protection
component: hdfs:Mover
v1: authentication
v2: integrity
testProject: hdfs
unitTest: org.apache.hadoop.hdfs.server.mover.TestMover#testMoverWithKeytabs
reconfPoint: -3
result: -1
failureMessage: Movement to ARCHIVE should be successful expected:<0> but was:<-3>
stackTrace: java.lang.AssertionError: Movement to ARCHIVE should be successful expected:<0> but was:<-3>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.apache.hadoop.hdfs.server.mover.TestMover.testWithinSameNode(TestMover.java:201)
	at org.apache.hadoop.hdfs.server.mover.TestMover.access$100(TestMover.java:101)
	at org.apache.hadoop.hdfs.server.mover.TestMover$3.run(TestMover.java:1017)
	at org.apache.hadoop.hdfs.server.mover.TestMover$3.run(TestMover.java:1013)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
	at org.apache.hadoop.hdfs.server.mover.TestMover.testMoverWithKeytabs(TestMover.java:1013)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)



Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is -1
v1v2 test failed !!!
reconf_parameter: hadoop.rpc.protection
component: hdfs:Mover
v1: authentication
v2: integrity
testProject: hdfs
unitTest: org.apache.hadoop.hdfs.server.mover.TestMover#testMoverWithKeytabs
reconfPoint: -3
result: -1
failureMessage: Movement to ARCHIVE should be successful expected:<0> but was:<-3>
stackTrace: java.lang.AssertionError: Movement to ARCHIVE should be successful expected:<0> but was:<-3>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.apache.hadoop.hdfs.server.mover.TestMover.testWithinSameNode(TestMover.java:201)
	at org.apache.hadoop.hdfs.server.mover.TestMover.access$100(TestMover.java:101)
	at org.apache.hadoop.hdfs.server.mover.TestMover$3.run(TestMover.java:1017)
	at org.apache.hadoop.hdfs.server.mover.TestMover$3.run(TestMover.java:1013)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
	at org.apache.hadoop.hdfs.server.mover.TestMover.testMoverWithKeytabs(TestMover.java:1013)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)



Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is -1
v1v2 test failed !!!
reconf_parameter: hadoop.rpc.protection
component: hdfs:Mover
v1: authentication
v2: integrity
testProject: hdfs
unitTest: org.apache.hadoop.hdfs.server.mover.TestMover#testMoverWithKeytabs
reconfPoint: -3
result: -1
failureMessage: Movement to ARCHIVE should be successful expected:<0> but was:<-3>
stackTrace: java.lang.AssertionError: Movement to ARCHIVE should be successful expected:<0> but was:<-3>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.apache.hadoop.hdfs.server.mover.TestMover.testWithinSameNode(TestMover.java:201)
	at org.apache.hadoop.hdfs.server.mover.TestMover.access$100(TestMover.java:101)
	at org.apache.hadoop.hdfs.server.mover.TestMover$3.run(TestMover.java:1017)
	at org.apache.hadoop.hdfs.server.mover.TestMover$3.run(TestMover.java:1013)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
	at org.apache.hadoop.hdfs.server.mover.TestMover.testMoverWithKeytabs(TestMover.java:1013)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)



Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is -1
v1v2 test failed !!!
reconf_parameter: hadoop.rpc.protection
component: hdfs:Mover
v1: authentication
v2: integrity
testProject: hdfs
unitTest: org.apache.hadoop.hdfs.server.mover.TestMover#testMoverWithKeytabs
reconfPoint: -3
result: -1
failureMessage: Movement to ARCHIVE should be successful expected:<0> but was:<-3>
stackTrace: java.lang.AssertionError: Movement to ARCHIVE should be successful expected:<0> but was:<-3>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.apache.hadoop.hdfs.server.mover.TestMover.testWithinSameNode(TestMover.java:201)
	at org.apache.hadoop.hdfs.server.mover.TestMover.access$100(TestMover.java:101)
	at org.apache.hadoop.hdfs.server.mover.TestMover$3.run(TestMover.java:1017)
	at org.apache.hadoop.hdfs.server.mover.TestMover$3.run(TestMover.java:1013)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
	at org.apache.hadoop.hdfs.server.mover.TestMover.testMoverWithKeytabs(TestMover.java:1013)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)



Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1
early stop after 10 is satisfied
v1v2 failed with probability 10 out of 10
v1v1v2v2 failed with probability 0 out of 10
result: might be true error
Total execution time in seconds : 1396
