reconf_parameter: dfs.bytes-per-checksum
component: hdfs:NameNode
v1: 512
v2: 32
testProject: hdfs
unitTest: org.apache.hadoop.fs.TestSymlinkHdfsFileContext#testAccessFileViaInterSymlinkAbsTarget
reconfPoint: 1
result: -1

Test vvMode=v1v2
tr.result is -1
v1v2 test failed !!!
reconf_parameter: dfs.bytes-per-checksum
component: hdfs:NameNode
v1: 512
v2: 32
testProject: hdfs
unitTest: org.apache.hadoop.fs.TestSymlinkHdfsFileContext#testAccessFileViaInterSymlinkAbsTarget
reconfPoint: 1
result: -1
failureMessage: `/test1/fileNew': Fail to get block MD5 for LocatedBlock{BP-1420705871-172.17.0.8-1597059047093:blk_1073741827_1003; getBlockSize()=8192; corrupt=false; offset=16384; locs=[DatanodeInfoWithStorage[127.0.0.1:46669,DS-73a212ce-b2df-42aa-95a8-763f20c5f3a0,DISK]]}
stackTrace: org.apache.hadoop.fs.PathIOException: `/test1/fileNew': Fail to get block MD5 for LocatedBlock{BP-1420705871-172.17.0.8-1597059047093:blk_1073741827_1003; getBlockSize()=8192; corrupt=false; offset=16384; locs=[DatanodeInfoWithStorage[127.0.0.1:46669,DS-73a212ce-b2df-42aa-95a8-763f20c5f3a0,DISK]]}
	at org.apache.hadoop.hdfs.FileChecksumHelper$ReplicatedFileChecksumComputer.checksumBlocks(FileChecksumHelper.java:507)
	at org.apache.hadoop.hdfs.FileChecksumHelper$FileChecksumComputer.compute(FileChecksumHelper.java:252)
	at org.apache.hadoop.hdfs.DFSClient.getFileChecksumInternal(DFSClient.java:1790)
	at org.apache.hadoop.hdfs.DFSClient.getFileChecksumWithCombineMode(DFSClient.java:1810)
	at org.apache.hadoop.fs.Hdfs.getFileChecksum(Hdfs.java:135)
	at org.apache.hadoop.fs.FileContext$14.next(FileContext.java:1187)
	at org.apache.hadoop.fs.FileContext$14.next(FileContext.java:1183)
	at org.apache.hadoop.fs.FSLinkResolver.resolve(FSLinkResolver.java:90)
	at org.apache.hadoop.fs.FileContext.getFileChecksum(FileContext.java:1189)
	at org.apache.hadoop.fs.FileContextTestWrapper.getFileChecksum(FileContextTestWrapper.java:296)
	at org.apache.hadoop.fs.SymlinkBaseTest.testAccessFileViaInterSymlinkAbsTarget(SymlinkBaseTest.java:1293)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)



Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is -1
v1v2 test failed !!!
reconf_parameter: dfs.bytes-per-checksum
component: hdfs:NameNode
v1: 512
v2: 32
testProject: hdfs
unitTest: org.apache.hadoop.fs.TestSymlinkHdfsFileContext#testAccessFileViaInterSymlinkAbsTarget
reconfPoint: 1
result: -1
failureMessage: `/test1/fileNew': Fail to get block MD5 for LocatedBlock{BP-185029606-172.17.0.8-1597059122866:blk_1073741827_1003; getBlockSize()=8192; corrupt=false; offset=16384; locs=[DatanodeInfoWithStorage[127.0.0.1:45866,DS-563d7691-f34d-4843-8bbd-384c063f7a74,DISK]]}
stackTrace: org.apache.hadoop.fs.PathIOException: `/test1/fileNew': Fail to get block MD5 for LocatedBlock{BP-185029606-172.17.0.8-1597059122866:blk_1073741827_1003; getBlockSize()=8192; corrupt=false; offset=16384; locs=[DatanodeInfoWithStorage[127.0.0.1:45866,DS-563d7691-f34d-4843-8bbd-384c063f7a74,DISK]]}
	at org.apache.hadoop.hdfs.FileChecksumHelper$ReplicatedFileChecksumComputer.checksumBlocks(FileChecksumHelper.java:507)
	at org.apache.hadoop.hdfs.FileChecksumHelper$FileChecksumComputer.compute(FileChecksumHelper.java:252)
	at org.apache.hadoop.hdfs.DFSClient.getFileChecksumInternal(DFSClient.java:1790)
	at org.apache.hadoop.hdfs.DFSClient.getFileChecksumWithCombineMode(DFSClient.java:1810)
	at org.apache.hadoop.fs.Hdfs.getFileChecksum(Hdfs.java:135)
	at org.apache.hadoop.fs.FileContext$14.next(FileContext.java:1187)
	at org.apache.hadoop.fs.FileContext$14.next(FileContext.java:1183)
	at org.apache.hadoop.fs.FSLinkResolver.resolve(FSLinkResolver.java:90)
	at org.apache.hadoop.fs.FileContext.getFileChecksum(FileContext.java:1189)
	at org.apache.hadoop.fs.FileContextTestWrapper.getFileChecksum(FileContextTestWrapper.java:296)
	at org.apache.hadoop.fs.SymlinkBaseTest.testAccessFileViaInterSymlinkAbsTarget(SymlinkBaseTest.java:1293)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)



Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is -1
v1v2 test failed !!!
reconf_parameter: dfs.bytes-per-checksum
component: hdfs:NameNode
v1: 512
v2: 32
testProject: hdfs
unitTest: org.apache.hadoop.fs.TestSymlinkHdfsFileContext#testAccessFileViaInterSymlinkAbsTarget
reconfPoint: 1
result: -1
failureMessage: `/test1/fileNew': Fail to get block MD5 for LocatedBlock{BP-1472121837-172.17.0.8-1597059193328:blk_1073741827_1003; getBlockSize()=8192; corrupt=false; offset=16384; locs=[DatanodeInfoWithStorage[127.0.0.1:43934,DS-749f2db8-9a33-4a8f-8b81-72010df47c46,DISK]]}
stackTrace: org.apache.hadoop.fs.PathIOException: `/test1/fileNew': Fail to get block MD5 for LocatedBlock{BP-1472121837-172.17.0.8-1597059193328:blk_1073741827_1003; getBlockSize()=8192; corrupt=false; offset=16384; locs=[DatanodeInfoWithStorage[127.0.0.1:43934,DS-749f2db8-9a33-4a8f-8b81-72010df47c46,DISK]]}
	at org.apache.hadoop.hdfs.FileChecksumHelper$ReplicatedFileChecksumComputer.checksumBlocks(FileChecksumHelper.java:507)
	at org.apache.hadoop.hdfs.FileChecksumHelper$FileChecksumComputer.compute(FileChecksumHelper.java:252)
	at org.apache.hadoop.hdfs.DFSClient.getFileChecksumInternal(DFSClient.java:1790)
	at org.apache.hadoop.hdfs.DFSClient.getFileChecksumWithCombineMode(DFSClient.java:1810)
	at org.apache.hadoop.fs.Hdfs.getFileChecksum(Hdfs.java:135)
	at org.apache.hadoop.fs.FileContext$14.next(FileContext.java:1187)
	at org.apache.hadoop.fs.FileContext$14.next(FileContext.java:1183)
	at org.apache.hadoop.fs.FSLinkResolver.resolve(FSLinkResolver.java:90)
	at org.apache.hadoop.fs.FileContext.getFileChecksum(FileContext.java:1189)
	at org.apache.hadoop.fs.FileContextTestWrapper.getFileChecksum(FileContextTestWrapper.java:296)
	at org.apache.hadoop.fs.SymlinkBaseTest.testAccessFileViaInterSymlinkAbsTarget(SymlinkBaseTest.java:1293)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)



Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is -1
v1v2 test failed !!!
reconf_parameter: dfs.bytes-per-checksum
component: hdfs:NameNode
v1: 512
v2: 32
testProject: hdfs
unitTest: org.apache.hadoop.fs.TestSymlinkHdfsFileContext#testAccessFileViaInterSymlinkAbsTarget
reconfPoint: 1
result: -1
failureMessage: `/test1/fileNew': Fail to get block MD5 for LocatedBlock{BP-503530158-172.17.0.8-1597059269332:blk_1073741827_1003; getBlockSize()=8192; corrupt=false; offset=16384; locs=[DatanodeInfoWithStorage[127.0.0.1:40525,DS-a9fbd27c-f696-4e3e-916a-79a5e25f21bb,DISK]]}
stackTrace: org.apache.hadoop.fs.PathIOException: `/test1/fileNew': Fail to get block MD5 for LocatedBlock{BP-503530158-172.17.0.8-1597059269332:blk_1073741827_1003; getBlockSize()=8192; corrupt=false; offset=16384; locs=[DatanodeInfoWithStorage[127.0.0.1:40525,DS-a9fbd27c-f696-4e3e-916a-79a5e25f21bb,DISK]]}
	at org.apache.hadoop.hdfs.FileChecksumHelper$ReplicatedFileChecksumComputer.checksumBlocks(FileChecksumHelper.java:507)
	at org.apache.hadoop.hdfs.FileChecksumHelper$FileChecksumComputer.compute(FileChecksumHelper.java:252)
	at org.apache.hadoop.hdfs.DFSClient.getFileChecksumInternal(DFSClient.java:1790)
	at org.apache.hadoop.hdfs.DFSClient.getFileChecksumWithCombineMode(DFSClient.java:1810)
	at org.apache.hadoop.fs.Hdfs.getFileChecksum(Hdfs.java:135)
	at org.apache.hadoop.fs.FileContext$14.next(FileContext.java:1187)
	at org.apache.hadoop.fs.FileContext$14.next(FileContext.java:1183)
	at org.apache.hadoop.fs.FSLinkResolver.resolve(FSLinkResolver.java:90)
	at org.apache.hadoop.fs.FileContext.getFileChecksum(FileContext.java:1189)
	at org.apache.hadoop.fs.FileContextTestWrapper.getFileChecksum(FileContextTestWrapper.java:296)
	at org.apache.hadoop.fs.SymlinkBaseTest.testAccessFileViaInterSymlinkAbsTarget(SymlinkBaseTest.java:1293)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)



Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is -1
v1v2 test failed !!!
reconf_parameter: dfs.bytes-per-checksum
component: hdfs:NameNode
v1: 512
v2: 32
testProject: hdfs
unitTest: org.apache.hadoop.fs.TestSymlinkHdfsFileContext#testAccessFileViaInterSymlinkAbsTarget
reconfPoint: 1
result: -1
failureMessage: `/test1/fileNew': Fail to get block MD5 for LocatedBlock{BP-1582474432-172.17.0.8-1597059352823:blk_1073741827_1003; getBlockSize()=8192; corrupt=false; offset=16384; locs=[DatanodeInfoWithStorage[127.0.0.1:38638,DS-62d6b943-c5db-41c8-b788-bfb8c7c73418,DISK]]}
stackTrace: org.apache.hadoop.fs.PathIOException: `/test1/fileNew': Fail to get block MD5 for LocatedBlock{BP-1582474432-172.17.0.8-1597059352823:blk_1073741827_1003; getBlockSize()=8192; corrupt=false; offset=16384; locs=[DatanodeInfoWithStorage[127.0.0.1:38638,DS-62d6b943-c5db-41c8-b788-bfb8c7c73418,DISK]]}
	at org.apache.hadoop.hdfs.FileChecksumHelper$ReplicatedFileChecksumComputer.checksumBlocks(FileChecksumHelper.java:507)
	at org.apache.hadoop.hdfs.FileChecksumHelper$FileChecksumComputer.compute(FileChecksumHelper.java:252)
	at org.apache.hadoop.hdfs.DFSClient.getFileChecksumInternal(DFSClient.java:1790)
	at org.apache.hadoop.hdfs.DFSClient.getFileChecksumWithCombineMode(DFSClient.java:1810)
	at org.apache.hadoop.fs.Hdfs.getFileChecksum(Hdfs.java:135)
	at org.apache.hadoop.fs.FileContext$14.next(FileContext.java:1187)
	at org.apache.hadoop.fs.FileContext$14.next(FileContext.java:1183)
	at org.apache.hadoop.fs.FSLinkResolver.resolve(FSLinkResolver.java:90)
	at org.apache.hadoop.fs.FileContext.getFileChecksum(FileContext.java:1189)
	at org.apache.hadoop.fs.FileContextTestWrapper.getFileChecksum(FileContextTestWrapper.java:296)
	at org.apache.hadoop.fs.SymlinkBaseTest.testAccessFileViaInterSymlinkAbsTarget(SymlinkBaseTest.java:1293)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)



Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is -1
v1v2 test failed !!!
reconf_parameter: dfs.bytes-per-checksum
component: hdfs:NameNode
v1: 512
v2: 32
testProject: hdfs
unitTest: org.apache.hadoop.fs.TestSymlinkHdfsFileContext#testAccessFileViaInterSymlinkAbsTarget
reconfPoint: 1
result: -1
failureMessage: `/test1/fileNew': Fail to get block MD5 for LocatedBlock{BP-1107642276-172.17.0.8-1597059424167:blk_1073741827_1003; getBlockSize()=8192; corrupt=false; offset=16384; locs=[DatanodeInfoWithStorage[127.0.0.1:40584,DS-0678a4c8-9303-4646-8eb1-1a065548517b,DISK]]}
stackTrace: org.apache.hadoop.fs.PathIOException: `/test1/fileNew': Fail to get block MD5 for LocatedBlock{BP-1107642276-172.17.0.8-1597059424167:blk_1073741827_1003; getBlockSize()=8192; corrupt=false; offset=16384; locs=[DatanodeInfoWithStorage[127.0.0.1:40584,DS-0678a4c8-9303-4646-8eb1-1a065548517b,DISK]]}
	at org.apache.hadoop.hdfs.FileChecksumHelper$ReplicatedFileChecksumComputer.checksumBlocks(FileChecksumHelper.java:507)
	at org.apache.hadoop.hdfs.FileChecksumHelper$FileChecksumComputer.compute(FileChecksumHelper.java:252)
	at org.apache.hadoop.hdfs.DFSClient.getFileChecksumInternal(DFSClient.java:1790)
	at org.apache.hadoop.hdfs.DFSClient.getFileChecksumWithCombineMode(DFSClient.java:1810)
	at org.apache.hadoop.fs.Hdfs.getFileChecksum(Hdfs.java:135)
	at org.apache.hadoop.fs.FileContext$14.next(FileContext.java:1187)
	at org.apache.hadoop.fs.FileContext$14.next(FileContext.java:1183)
	at org.apache.hadoop.fs.FSLinkResolver.resolve(FSLinkResolver.java:90)
	at org.apache.hadoop.fs.FileContext.getFileChecksum(FileContext.java:1189)
	at org.apache.hadoop.fs.FileContextTestWrapper.getFileChecksum(FileContextTestWrapper.java:296)
	at org.apache.hadoop.fs.SymlinkBaseTest.testAccessFileViaInterSymlinkAbsTarget(SymlinkBaseTest.java:1293)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)



Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is -1
v1v2 test failed !!!
reconf_parameter: dfs.bytes-per-checksum
component: hdfs:NameNode
v1: 512
v2: 32
testProject: hdfs
unitTest: org.apache.hadoop.fs.TestSymlinkHdfsFileContext#testAccessFileViaInterSymlinkAbsTarget
reconfPoint: 1
result: -1
failureMessage: `/test1/fileNew': Fail to get block MD5 for LocatedBlock{BP-2016987433-172.17.0.8-1597059496517:blk_1073741827_1003; getBlockSize()=8192; corrupt=false; offset=16384; locs=[DatanodeInfoWithStorage[127.0.0.1:33492,DS-e750a522-1bc0-4ce8-addf-685aeec7404e,DISK]]}
stackTrace: org.apache.hadoop.fs.PathIOException: `/test1/fileNew': Fail to get block MD5 for LocatedBlock{BP-2016987433-172.17.0.8-1597059496517:blk_1073741827_1003; getBlockSize()=8192; corrupt=false; offset=16384; locs=[DatanodeInfoWithStorage[127.0.0.1:33492,DS-e750a522-1bc0-4ce8-addf-685aeec7404e,DISK]]}
	at org.apache.hadoop.hdfs.FileChecksumHelper$ReplicatedFileChecksumComputer.checksumBlocks(FileChecksumHelper.java:507)
	at org.apache.hadoop.hdfs.FileChecksumHelper$FileChecksumComputer.compute(FileChecksumHelper.java:252)
	at org.apache.hadoop.hdfs.DFSClient.getFileChecksumInternal(DFSClient.java:1790)
	at org.apache.hadoop.hdfs.DFSClient.getFileChecksumWithCombineMode(DFSClient.java:1810)
	at org.apache.hadoop.fs.Hdfs.getFileChecksum(Hdfs.java:135)
	at org.apache.hadoop.fs.FileContext$14.next(FileContext.java:1187)
	at org.apache.hadoop.fs.FileContext$14.next(FileContext.java:1183)
	at org.apache.hadoop.fs.FSLinkResolver.resolve(FSLinkResolver.java:90)
	at org.apache.hadoop.fs.FileContext.getFileChecksum(FileContext.java:1189)
	at org.apache.hadoop.fs.FileContextTestWrapper.getFileChecksum(FileContextTestWrapper.java:296)
	at org.apache.hadoop.fs.SymlinkBaseTest.testAccessFileViaInterSymlinkAbsTarget(SymlinkBaseTest.java:1293)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)



Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is -1
v1v2 test failed !!!
reconf_parameter: dfs.bytes-per-checksum
component: hdfs:NameNode
v1: 512
v2: 32
testProject: hdfs
unitTest: org.apache.hadoop.fs.TestSymlinkHdfsFileContext#testAccessFileViaInterSymlinkAbsTarget
reconfPoint: 1
result: -1
failureMessage: `/test1/fileNew': Fail to get block MD5 for LocatedBlock{BP-1923896793-172.17.0.8-1597059572741:blk_1073741827_1003; getBlockSize()=8192; corrupt=false; offset=16384; locs=[DatanodeInfoWithStorage[127.0.0.1:35681,DS-68b7e496-f382-4776-947d-74ff34c2b63b,DISK]]}
stackTrace: org.apache.hadoop.fs.PathIOException: `/test1/fileNew': Fail to get block MD5 for LocatedBlock{BP-1923896793-172.17.0.8-1597059572741:blk_1073741827_1003; getBlockSize()=8192; corrupt=false; offset=16384; locs=[DatanodeInfoWithStorage[127.0.0.1:35681,DS-68b7e496-f382-4776-947d-74ff34c2b63b,DISK]]}
	at org.apache.hadoop.hdfs.FileChecksumHelper$ReplicatedFileChecksumComputer.checksumBlocks(FileChecksumHelper.java:507)
	at org.apache.hadoop.hdfs.FileChecksumHelper$FileChecksumComputer.compute(FileChecksumHelper.java:252)
	at org.apache.hadoop.hdfs.DFSClient.getFileChecksumInternal(DFSClient.java:1790)
	at org.apache.hadoop.hdfs.DFSClient.getFileChecksumWithCombineMode(DFSClient.java:1810)
	at org.apache.hadoop.fs.Hdfs.getFileChecksum(Hdfs.java:135)
	at org.apache.hadoop.fs.FileContext$14.next(FileContext.java:1187)
	at org.apache.hadoop.fs.FileContext$14.next(FileContext.java:1183)
	at org.apache.hadoop.fs.FSLinkResolver.resolve(FSLinkResolver.java:90)
	at org.apache.hadoop.fs.FileContext.getFileChecksum(FileContext.java:1189)
	at org.apache.hadoop.fs.FileContextTestWrapper.getFileChecksum(FileContextTestWrapper.java:296)
	at org.apache.hadoop.fs.SymlinkBaseTest.testAccessFileViaInterSymlinkAbsTarget(SymlinkBaseTest.java:1293)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)



Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is -1
v1v2 test failed !!!
reconf_parameter: dfs.bytes-per-checksum
component: hdfs:NameNode
v1: 512
v2: 32
testProject: hdfs
unitTest: org.apache.hadoop.fs.TestSymlinkHdfsFileContext#testAccessFileViaInterSymlinkAbsTarget
reconfPoint: 1
result: -1
failureMessage: `/test1/fileNew': Fail to get block MD5 for LocatedBlock{BP-2017621591-172.17.0.8-1597059652933:blk_1073741827_1003; getBlockSize()=8192; corrupt=false; offset=16384; locs=[DatanodeInfoWithStorage[127.0.0.1:37607,DS-aa6ce201-915a-409c-936e-eec0d262260f,DISK]]}
stackTrace: org.apache.hadoop.fs.PathIOException: `/test1/fileNew': Fail to get block MD5 for LocatedBlock{BP-2017621591-172.17.0.8-1597059652933:blk_1073741827_1003; getBlockSize()=8192; corrupt=false; offset=16384; locs=[DatanodeInfoWithStorage[127.0.0.1:37607,DS-aa6ce201-915a-409c-936e-eec0d262260f,DISK]]}
	at org.apache.hadoop.hdfs.FileChecksumHelper$ReplicatedFileChecksumComputer.checksumBlocks(FileChecksumHelper.java:507)
	at org.apache.hadoop.hdfs.FileChecksumHelper$FileChecksumComputer.compute(FileChecksumHelper.java:252)
	at org.apache.hadoop.hdfs.DFSClient.getFileChecksumInternal(DFSClient.java:1790)
	at org.apache.hadoop.hdfs.DFSClient.getFileChecksumWithCombineMode(DFSClient.java:1810)
	at org.apache.hadoop.fs.Hdfs.getFileChecksum(Hdfs.java:135)
	at org.apache.hadoop.fs.FileContext$14.next(FileContext.java:1187)
	at org.apache.hadoop.fs.FileContext$14.next(FileContext.java:1183)
	at org.apache.hadoop.fs.FSLinkResolver.resolve(FSLinkResolver.java:90)
	at org.apache.hadoop.fs.FileContext.getFileChecksum(FileContext.java:1189)
	at org.apache.hadoop.fs.FileContextTestWrapper.getFileChecksum(FileContextTestWrapper.java:296)
	at org.apache.hadoop.fs.SymlinkBaseTest.testAccessFileViaInterSymlinkAbsTarget(SymlinkBaseTest.java:1293)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)



Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is -1
v1v2 test failed !!!
reconf_parameter: dfs.bytes-per-checksum
component: hdfs:NameNode
v1: 512
v2: 32
testProject: hdfs
unitTest: org.apache.hadoop.fs.TestSymlinkHdfsFileContext#testAccessFileViaInterSymlinkAbsTarget
reconfPoint: 1
result: -1
failureMessage: `/test1/fileNew': Fail to get block MD5 for LocatedBlock{BP-1547144031-172.17.0.8-1597059728002:blk_1073741827_1003; getBlockSize()=8192; corrupt=false; offset=16384; locs=[DatanodeInfoWithStorage[127.0.0.1:36008,DS-b068ac67-0f53-4e49-aa8a-0192ccb8b1e5,DISK]]}
stackTrace: org.apache.hadoop.fs.PathIOException: `/test1/fileNew': Fail to get block MD5 for LocatedBlock{BP-1547144031-172.17.0.8-1597059728002:blk_1073741827_1003; getBlockSize()=8192; corrupt=false; offset=16384; locs=[DatanodeInfoWithStorage[127.0.0.1:36008,DS-b068ac67-0f53-4e49-aa8a-0192ccb8b1e5,DISK]]}
	at org.apache.hadoop.hdfs.FileChecksumHelper$ReplicatedFileChecksumComputer.checksumBlocks(FileChecksumHelper.java:507)
	at org.apache.hadoop.hdfs.FileChecksumHelper$FileChecksumComputer.compute(FileChecksumHelper.java:252)
	at org.apache.hadoop.hdfs.DFSClient.getFileChecksumInternal(DFSClient.java:1790)
	at org.apache.hadoop.hdfs.DFSClient.getFileChecksumWithCombineMode(DFSClient.java:1810)
	at org.apache.hadoop.fs.Hdfs.getFileChecksum(Hdfs.java:135)
	at org.apache.hadoop.fs.FileContext$14.next(FileContext.java:1187)
	at org.apache.hadoop.fs.FileContext$14.next(FileContext.java:1183)
	at org.apache.hadoop.fs.FSLinkResolver.resolve(FSLinkResolver.java:90)
	at org.apache.hadoop.fs.FileContext.getFileChecksum(FileContext.java:1189)
	at org.apache.hadoop.fs.FileContextTestWrapper.getFileChecksum(FileContextTestWrapper.java:296)
	at org.apache.hadoop.fs.SymlinkBaseTest.testAccessFileViaInterSymlinkAbsTarget(SymlinkBaseTest.java:1293)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)



Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1
early stop after 10 is satisfied
v1v2 failed with probability 10 out of 10
v1v1v2v2 failed with probability 0 out of 10
result: might be true error
Total execution time in seconds : 755
